//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seas0nPass {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seas0nPass.ScriptResource", typeof(ScriptResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bspatch
        ///dfu
        ///dmg-bin
        ///hdutil
        ///hfsplus
        ///tether
        ///vfdecrypt
        ///xpwntool
        ///.
        /// </summary>
        internal static string ProgramsToKill {
            get {
                return ResourceManager.GetString("ProgramsToKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodo: Internet Security;cmdagent;cfp
        ///Symantec: Norton Internet Security;ccSvcHst
        ///McAfee: Total Protection;mcagent;McSvHost;mfefire;mfevtps;mcshield
        ///Kaspersky: Internet Security;avp
        ///ESET: Smart Security;ekrn
        ///Avast Free AntiVirus;AvastSvc
        ///AVG: Internet Security;avgrsx;avgcsrvx;AVGIDSAge;avgfvs;avgwdsvc;avgtray
        ///Avira: Premium Security Suite;avgnt;avmailc;AVWEBGRD;avshadow;avguard;sched
        ///BitDefender: Internet Security Suite;vsserv;updatesrv;bdagent;pchookla
        ///Webroot: Internet Security Complete;AEI;SSU; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgramsToWarn {
            get {
                return ResourceManager.GetString("ProgramsToWarn", resourceCulture);
            }
        }
    }
}
