//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seas0nPass {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seas0nPass.ScriptResource", typeof(ScriptResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\xpwntool.exe .\UNZIPPED_ORIGINAL\038-0318-001.dmg  ipsw/038-0318-001.dmg -iv 7c256102d0580b960213540965618b5b -k 5d4e967158ab75ba27ec281bff4e714dacc88123ea4913ae2bee6a719c15496c.
        /// </summary>
        internal static string _421_010_decrypt_ramdisk {
            get {
                return ResourceManager.GetString("_421_010_decrypt_ramdisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our.dmg ls /usr/sbin
        ///.\bin\hfsplus.exe .\tmp\our.dmg extract /usr/sbin/asr .\tmp\asr
        ///.\bin\hfsplus.exe .\tmp\our.dmg rm /usr/sbin/asr
        ///.\bin\hfsplus.exe .\tmp\our.dmg ls /usr/sbin
        ///.\bin\hfsplus.exe .\tmp\our.dmg grow 16542208
        ///.\bin\bspatch.exe .\tmp\asr .\tmp\asr.patched .\8C154\asr.patch
        ///.\bin\hfsplus.exe .\tmp\our.dmg add .\tmp\asr.patched /usr/sbin/asr
        ///.\bin\hfsplus.exe .\tmp\our.dmg ls /usr/sbin
        ///.\bin\hfsplus.exe .\tmp\our.dmg chmod 755 /usr/sbin/asr 
        ///.\bin\hfsplus.exe .\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _421_020_patch_asr {
            get {
                return ResourceManager.GetString("_421_020_patch_asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\xpwntool.exe .\tmp\our.dmg .\output\038-0318-001.dmg -iv 7c256102d0580b960213540965618b5b -k 5d4e967158ab75ba27ec281bff4e714dacc88123ea4913ae2bee6a719c15496c -t .\UNZIPPED_ORIGINAL\038-0318-001.dmg 
        ///.
        /// </summary>
        internal static string _421_030_encrypt_ramdisk {
            get {
                return ResourceManager.GetString("_421_030_encrypt_ramdisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\vfdecrypt -i .\UNZIPPED_ORIGINAL\038-0316-001.dmg -k 5407d28e075f5a2e06fddb7ad00123aa5a528bd6c2850d5fa0908a4dcae7dd3e00a9cdb2 -o ipsw/038-0316-001.dmg.
        /// </summary>
        internal static string _421_040_decrypt_filesystem {
            get {
                return ResourceManager.GetString("_421_040_decrypt_filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\dmg-bin.exe extract .\tmp\our-big.dmg .\tmp\our-big-hfsimage.dmg.
        /// </summary>
        internal static string _421_050_unpack_filesystem_image {
            get {
                return ResourceManager.GetString("_421_050_unpack_filesystem_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg extract /etc/fstab .\tmp\fstab
        ///.\bin\bspatch.exe .\tmp\fstab .\tmp\fstab.patched .\8C154\fstab.patch
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /etc
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg rm /etc/fstab
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /etc
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\tmp\fstab.patched /etc/fstab
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /etc
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 644 /etc/f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _421_060_patch_fstab {
            get {
                return ResourceManager.GetString("_421_060_patch_fstab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg extract /Applications/AppleTV.app/AppleTV .\tmp\AppleTV
        ///.\bin\bspatch.exe .\tmp\AppleTV .\tmp\AppleTV.patched .\8C154\AppleTV.patch
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /Applications/AppleTV.app
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg rm /Applications/AppleTV.app/AppleTV
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /Applications/AppleTV.app
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\tmp\AppleTV.patched /Applications/AppleTV.app/App [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _421_061_patch_appletv {
            get {
                return ResourceManager.GetString("_421_061_patch_appletv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg extract /System/Library/Lockdown/Services.plist .\tmp\Services.plist
        ///.\bin\bspatch.exe .\tmp\Services.plist .\tmp\Services.plist.patched .\8C154\Services.patch
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /System/Library/Lockdown
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg rm /System/Library/Lockdown/Services.plist
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /System/Library/Lockdown
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\tmp\Services.plis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _421_062_patch_Services_plist {
            get {
                return ResourceManager.GetString("_421_062_patch_Services_plist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /usr/lib/
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\8C154\hfs_mdb  /usr/lib/hfs_mdb
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /usr/lib/
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 755 /usr/lib/hfs_mdb
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /usr/lib/.
        /// </summary>
        internal static string _421_063_add_hfs_mdb {
            get {
                return ResourceManager.GetString("_421_063_add_hfs_mdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /usr/lib/
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\8C154\kern_sploit  /usr/lib/kern_sploit
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /usr/lib/
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 755 /usr/lib/kern_sploit
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /usr/lib/.
        /// </summary>
        internal static string _421_064_add_kern_sploit {
            get {
                return ResourceManager.GetString("_421_064_add_kern_sploit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg extract /sbin/launchd .\tmp\launchd
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg rm /sbin/launchd
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\8C154\punchd /sbin/launchd
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 755 /sbin/launchd
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\tmp\launchd /sbin/punchd
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 555 /sbin/punchd
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /sbin
        ///.
        /// </summary>
        internal static string _421_065_add_punchd {
            get {
                return ResourceManager.GetString("_421_065_add_punchd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg untar .\tmp\cydia\cydia.tar
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\DEBS\asubstrate.deb /private/var/root/Media/Cydia/AutoInstall/asubstrate.deb
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 644 /private/var/root/Media/Cydia/AutoInstall/asubstrate.deb
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\DEBS\awkwardtv.deb /private/var/root/Media/Cydia/AutoInstall/awkwardtv.deb
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 644 /private/var/r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _421_080_add_cydia_to_image {
            get {
                return ResourceManager.GetString("_421_080_add_cydia_to_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mkdir /var/stash
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mkdir /usr/include
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv      /Applications      /var/stash/Applications
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv      /Library/Ringtones /var/stash/Ringtones
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv      /Library/Wallpaper /var/stash/Wallpaper
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv      /usr/bin           /var/stash/bin
        ///.\bin\hfspl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _421_081_create_symlinks {
            get {
                return ResourceManager.GetString("_421_081_create_symlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\8C154\uncompress /bin/uncompress
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 755 /bin/uncompress
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /bin.
        /// </summary>
        internal static string _421_082_add_uncompress {
            get {
                return ResourceManager.GetString("_421_082_add_uncompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\dmg-bin.exe build .\tmp\our-big-hfsimage.dmg .\output\038-0316-001.dmg.
        /// </summary>
        internal static string _421_090_pack_filesystem_image {
            get {
                return ResourceManager.GetString("_421_090_pack_filesystem_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\xpwntool.exe .\OUTPUT\Firmware\dfu\iBSS.k66ap.RELEASE.dfu  .\OUTPUT\Firmware\dfu\decrypted.dfu -iv 03baadf8801e8b7cdcee5a9f53609d0c -k c9f8bd4e52530ec8ef3e2b5926777f624061a38d09f07785287de6e88353f752
        ///.\bin\bspatch.exe .\OUTPUT\Firmware\dfu\decrypted.dfu .\OUTPUT\Firmware\dfu\patched.dfu .\8C154\iBSS.k66ap.RELEASE.patch
        ///.\bin\xpwntool.exe .\OUTPUT\Firmware\dfu\patched.dfu .\OUTPUT\Firmware\dfu\encrypted.dfu -iv 03baadf8801e8b7cdcee5a9f53609d0c -k c9f8bd4e52530ec8ef3e2b5926777f624061a38d09f07785287de6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _421_110_patch_dfu {
            get {
                return ResourceManager.GetString("_421_110_patch_dfu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\xpwntool.exe .\UNZIPPED_ORIGINAL\038-0791-023.dmg ipsw/038-0791-023.dmg.
        /// </summary>
        internal static string _43_010_decrypt_ramdisk {
            get {
                return ResourceManager.GetString("_43_010_decrypt_ramdisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our.dmg ls /usr/sbin
        ///.\bin\hfsplus.exe .\tmp\our.dmg extract /usr/sbin/asr .\tmp\asr
        ///.\bin\hfsplus.exe .\tmp\our.dmg mv /usr/sbin/asr /usr/sbin/asr_backup
        ///.\bin\hfsplus.exe .\tmp\our.dmg ls /usr/sbin
        ///.\bin\hfsplus.exe .\tmp\our.dmg grow 25272320
        ///.\bin\hfsplus.exe .\tmp\our.dmg ls /usr/sbin
        ///.\bin\bspatch.exe .\tmp\asr .\tmp\asr.patched .\8F191m\asr.patch
        ///.\bin\hfsplus.exe .\tmp\our.dmg add .\tmp\asr.patched /usr/sbin/asr
        ///.\bin\hfsplus.exe .\tmp\our.dmg ls /usr/sbin
        ///.\bin\hfsp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _43_020_patch_asr {
            get {
                return ResourceManager.GetString("_43_020_patch_asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\xpwntool.exe .\tmp\our.dmg .\output\038-0791-023.dmg -t .\UNZIPPED_ORIGINAL\038-0791-023.dmg.
        /// </summary>
        internal static string _43_030_encrypt_ramdisk {
            get {
                return ResourceManager.GetString("_43_030_encrypt_ramdisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\vfdecrypt -i .\UNZIPPED_ORIGINAL\018-7896-152.dmg -k a30f67f64a546a28bfd5c6e2e43d14fd8111c55641fc6dc392891e2b14e7e8138db9344c -o ipsw/018-7896-152.dmg.
        /// </summary>
        internal static string _43_040_decrypt_filesystem {
            get {
                return ResourceManager.GetString("_43_040_decrypt_filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\dmg-bin.exe extract .\tmp\our-big.dmg .\tmp\our-big-hfsimage.dmg.
        /// </summary>
        internal static string _43_050_unpack_filesystem_image {
            get {
                return ResourceManager.GetString("_43_050_unpack_filesystem_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg extract /etc/fstab .\tmp\fstab
        ///.\bin\bspatch.exe .\tmp\fstab .\tmp\fstab.patched .\8F191m\fstab.patch
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /etc
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv /etc/fstab etc/fstab_backup
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /etc
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\tmp\fstab.patched /etc/fstab
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /etc
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _43_060_patch_fstab {
            get {
                return ResourceManager.GetString("_43_060_patch_fstab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg extract /Applications/AppleTV.app/AppleTV .\tmp\AppleTV
        ///.\bin\bspatch.exe .\tmp\AppleTV .\tmp\AppleTV.patched .\8F191m\AppleTV.patch
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /Applications/AppleTV.app
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv /Applications/AppleTV.app/AppleTV /Applications/AppleTV.app/AppleTV_backup
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /Applications/AppleTV.app
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\tmp\App [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _43_061_patch_appletv {
            get {
                return ResourceManager.GetString("_43_061_patch_appletv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg extract /System/Library/Lockdown/Services.plist .\tmp\Services.plist
        ///.\bin\bspatch.exe .\tmp\Services.plist .\tmp\Services.plist.patched .\8F191m\Services.patch
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /System/Library/Lockdown
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv /System/Library/Lockdown/Services.plist /System/Library/Lockdown/Services.plist_backup
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /System/Library/Lockdown
        ///.\bin\hfsplus.exe .\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _43_062_patch_Services_plist {
            get {
                return ResourceManager.GetString("_43_062_patch_Services_plist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg untar .\tmp\cydia\cydia.tar
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\DEBS\asubstrate.deb /private/var/root/Media/Cydia/AutoInstall/asubstrate.deb
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 644 /private/var/root/Media/Cydia/AutoInstall/asubstrate.deb
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\DEBS\awkwardtv.deb /private/var/root/Media/Cydia/AutoInstall/awkwardtv.deb
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 644 /private/var/r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _43_080_add_cydia_to_image {
            get {
                return ResourceManager.GetString("_43_080_add_cydia_to_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mkdir /var/stash
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mkdir /usr/include
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv      /Applications      /var/stash/Applications
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv      /Library/Ringtones /var/stash/Ringtones
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv      /Library/Wallpaper /var/stash/Wallpaper
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg mv      /usr/bin           /var/stash/bin
        ///.\bin\hfspl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _43_081_create_symlinks {
            get {
                return ResourceManager.GetString("_43_081_create_symlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\8F191m\uncompress /bin/uncompress
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg chmod 755 /bin/uncompress
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /bin.
        /// </summary>
        internal static string _43_082_add_uncompress {
            get {
                return ResourceManager.GetString("_43_082_add_uncompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /private/var/lib/dpkg
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg extract /private/var/lib/dpkg/status .\tmp\status
        ///.\bin\bspatch.exe .\tmp\status .\tmp\status.patched .\8F191m\status.patch
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg add .\tmp\status.patched /private/var/lib/dpkg/status.patched
        ///.\bin\hfsplus.exe .\tmp\our-big-hfsimage.dmg ls /private/var/lib/dpkg.
        /// </summary>
        internal static string _43_083_patch_status {
            get {
                return ResourceManager.GetString("_43_083_patch_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\dmg-bin.exe build .\tmp\our-big-hfsimage.dmg .\output\018-7896-152.dmg.
        /// </summary>
        internal static string _43_090_pack_filesystem_image {
            get {
                return ResourceManager.GetString("_43_090_pack_filesystem_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\bin\xpwntool.exe .\OUTPUT\Firmware\dfu\iBSS.k66ap.RELEASE.dfu  .\OUTPUT\Firmware\dfu\decrypted.dfu -iv 17742baec33113889e5cbfcaa12fb4f0 -k 998bd521b5b54641fbeb3f73d9959bae126db0bc7e90b7ede7440d3951016010
        ///.\bin\bspatch.exe .\OUTPUT\Firmware\dfu\decrypted.dfu .\OUTPUT\Firmware\dfu\patched.dfu .\8F191m\iBSS.k66ap.RELEASE.patch
        ///.\bin\xpwntool.exe .\OUTPUT\Firmware\dfu\patched.dfu .\OUTPUT\Firmware\dfu\encrypted.dfu -iv 17742baec33113889e5cbfcaa12fb4f0 -k 998bd521b5b54641fbeb3f73d9959bae126db0bc7e90b7ede7440 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _43_110_patch_dfu {
            get {
                return ResourceManager.GetString("_43_110_patch_dfu", resourceCulture);
            }
        }
        
        internal static byte[] Binaries {
            get {
                object obj = ResourceManager.GetObject("Binaries", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://appldnld.apple.com/AppleTV/061-9978.20101214.gmabr/AppleTV2,1_4.2.1_8C154_Restore.ipsw.
        /// </summary>
        internal static string firmware_421_8C154_Url {
            get {
                return ResourceManager.GetString("firmware_421_8C154_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://appldnld.apple.com/AppleTV/061-9584.20110308.Cxdew/AppleTV2,1_4.3_8F191m_Restore.ipsw.
        /// </summary>
        internal static string firmware_43_8F191m_Url {
            get {
                return ResourceManager.GetString("firmware_43_8F191m_Url", resourceCulture);
            }
        }
    }
}
